# The URL the site will be built for
base_url = "https://pjdevs.github.io"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = false

default_language = "en"

title = "Pierre-Jean MOREL"

description = "Pierre-Jean MOREL's portfolio"

[markdown]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = true

[extra]
enable_search = false
enable_sidebar = false
enable_adsense = false
enable_multilingue = false
#adsense_link = "https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?client=myclientid"

# Particle theme
description = "Some work I did on my own time"

username = "pjdevs"
user_photo = "pj.jpg"
user_title = "Pierre-Jean Morel"
user_email = "pjmorel@etu.uqac.ca"
user_github = " https://github.com/pjdevs"
user_linkedin = "https://www.linkedin.com/in/pierre-jean-morel-7a99221b6/"

# TODO: put links to tech

[[extra.techs]]
title = "Graphics"
description = "I am familiar with modern OpenGL and Direct 3D 11 and looking forward to learn a new modern API (Vulkan or D3D12)"
icons = [{image = false, name = "devicon-opengl-plain colored"}, {image = true, name = "dx11.png"}]

[[extra.techs]]
title = "Game"
description = "Side projects and courses at UQAC, Chicoutimi, Québec, Canada gave me solid skills in both Unreal Engine 5.1 and Unity"
icons = [
    {image = false, name = "devicon-unrealengine-plain colored"},
    {image = false, name = "devicon-unity-original colored"},
    {image = false, name = "devicon-godot-plain colored"}
]

[[extra.techs]]
title = "Dev"
description = "Most of my game development work was done in C++ and C#. I had to work or do academical projects with C and Python. I am a Rust lover !"
icons = [
    {image = false, name = "devicon-csharp-plain colored"},
    {image = false, name = "devicon-c-plain colored"},
    {image = false, name = "devicon-cplusplus-plain colored"},
    {image = false, name = "devicon-rust-plain colored"},
    {image = false, name = "devicon-python-plain colored"},
]

[[extra.techs]]
title = "Tools"
description = "All my academical and professional projects in teams were supported by either Git or Perforce."
icons = [
    {image = false, name = "devicon-git-plain colored"},
    {image = true, name = "p4v.png"}
]

[extra.social]
github = "https://github.com/pjdevs"
gitlab = "https://gitlab.com/pjdevs"
twitter = false
linkedin = "https://www.linkedin.com/in/pierre-jean-morel-7a99221b6/"
email = "pjmorel@etu.uqac.ca"
